resource "local_file" "pet" {
  filename = var.filename
  content = var.content
}

resource "random_pet" "my-pet" {
  prefix = var.prefix
  separator = var.separator
  length = var.length
} 
output pet-name {
  value = random_pet.my-pet.id
  description = "Recorf the value of pet ID generated by the random_pet resource"
}
